"""add model Users

Revision ID: 4ea7fcc5051f
Revises: f07314c54d3a
Create Date: 2026-06-03 13:46:51.670567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea7fcc5051f'
down_revision: Union[str, Sequence[str], None] = 'f07314c54d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # Очистка таблицы products перед добавлением нового столбца
    op.execute("DELETE FROM products") 

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
